[book]
title = "Rust 程序设计语言"
author = "Steve Klabnik and Carol Nichols, with Contributions from the Rust Community"
translator = "Rust 中文翻译项目组，Rust 中文社区"

[output.html]
additional-css = ["ferris.css", "theme/2018-edition.css"]
additional-js = ["ferris.js"]
git-repository-url = "https://github.com/rust-lang-cn/book-cn"
